server:
  port: 8084

spring:
  application:
    name: retrieval-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/rag_db
    username: rag_user
    password: rag_pass
    driver-class-name: org.postgresql.Driver
